"""Shared constants and field specifications for runner readiness."""

from __future__ import annotations

SCHEMA_VERSION = "1.0.0"
GENERATOR_VERSION = "0.1.0"
SOURCE_POLICY_VERSION = "1.0.0"
CACHE_POLICY_VERSION = "1.0.0"

SAFETY_NOTICE = {
    "version": "1.0.0",
    "medical_advice": False,
    "replaces_race_rules": False,
    "message": "This tool does not replace race rules, on-site safety, or professional medical judgment.",
}

FIELD_SPECS: dict[str, dict[str, object]] = {
    "weekly_km": {
        "label": "周跑量",
        "prompt_quick": "过去 1-2 周的周跑量大约多少公里？",
        "prompt_formal": "最近 8-12 周的周跑量大约多少公里？",
        "required_quick": True,
        "required_formal": True,
        "priority": "high",
        "sensitive": False,
        "kind": "number",
    },
    "weekly_elevation_m": {
        "label": "周爬升",
        "prompt_quick": "过去 1-2 周的周爬升大约多少米？",
        "prompt_formal": "最近 8-12 周的周爬升大约多少米？",
        "required_quick": True,
        "required_formal": True,
        "priority": "high",
        "sensitive": False,
        "kind": "number",
    },
    "continuity_weeks": {
        "label": "训练连续性",
        "prompt_quick": "你已经连续训练了多少周，没有明显中断？",
        "prompt_formal": "最近 8-12 周里，你的训练连续性如何？",
        "required_quick": True,
        "required_formal": True,
        "priority": "high",
        "sensitive": False,
        "kind": "number",
    },
    "longest_session_distance_km": {
        "label": "最长训练距离",
        "prompt_quick": "最近最长一次训练跑了多少公里？",
        "prompt_formal": "最近 8-12 周最长一次训练跑了多少公里？",
        "required_quick": True,
        "required_formal": True,
        "priority": "high",
        "sensitive": False,
        "kind": "number",
    },
    "longest_session_elevation_m": {
        "label": "最长训练爬升",
        "prompt_quick": "那次最长训练累计爬升大约多少米？",
        "prompt_formal": "那次最长训练累计爬升大约多少米？",
        "required_quick": False,
        "required_formal": True,
        "priority": "medium",
        "sensitive": False,
        "kind": "number",
    },
    "longest_session_duration_min": {
        "label": "最长训练用时",
        "prompt_quick": "那次最长训练大约用了多少分钟？",
        "prompt_formal": "那次最长训练大约用了多少分钟？",
        "required_quick": True,
        "required_formal": True,
        "priority": "high",
        "sensitive": False,
        "kind": "number",
    },
    "representative_races": {
        "label": "代表性比赛",
        "prompt_quick": "最近有没有一两场最能代表你状态的比赛？",
        "prompt_formal": "请列出最近 2-5 场代表性比赛，包含日期、距离、爬升和结果。",
        "required_quick": False,
        "required_formal": True,
        "priority": "high",
        "sensitive": False,
        "kind": "list",
    },
    "training_break_days": {
        "label": "训练中断",
        "prompt_quick": "最近有没有训练中断？中断了多久？",
        "prompt_formal": "最近 8-12 周有没有训练中断？中断了多久？",
        "required_quick": False,
        "required_formal": True,
        "priority": "high",
        "sensitive": True,
        "kind": "number",
    },
    "recovery_days": {
        "label": "恢复时间",
        "prompt_quick": "如果有中断，你恢复正常训练花了几天？",
        "prompt_formal": "如果有中断，你恢复正常训练花了几天？",
        "required_quick": False,
        "required_formal": True,
        "priority": "medium",
        "sensitive": True,
        "kind": "number",
    },
    "injury_status": {
        "label": "伤痛",
        "prompt_quick": "现在有伤痛、疼痛或不适吗？",
        "prompt_formal": "最近 8-12 周是否有伤痛、疼痛或不适？",
        "required_quick": True,
        "required_formal": True,
        "priority": "high",
        "sensitive": True,
        "kind": "text",
    },
    "illness_status": {
        "label": "疾病",
        "prompt_quick": "最近有发热、感染或明显生病吗？",
        "prompt_formal": "最近 8-12 周有疾病、发热或感染吗？",
        "required_quick": True,
        "required_formal": True,
        "priority": "high",
        "sensitive": True,
        "kind": "text",
    },
    "sleep_hours": {
        "label": "睡眠",
        "prompt_quick": "最近 3-7 晚平均睡了多少小时？",
        "prompt_formal": "最近 1-2 周平均睡了多少小时？",
        "required_quick": True,
        "required_formal": True,
        "priority": "high",
        "sensitive": True,
        "kind": "number",
    },
    "subjective_fatigue": {
        "label": "主观疲劳",
        "prompt_quick": "你现在的主观疲劳大概几分（0-10）？",
        "prompt_formal": "最近一周的主观疲劳大概几分（0-10）？",
        "required_quick": True,
        "required_formal": True,
        "priority": "high",
        "sensitive": True,
        "kind": "number",
    },
    "night_experience": {
        "label": "夜间经验",
        "prompt_quick": "你有夜跑或夜赛经验吗？",
        "prompt_formal": "你有夜间训练或夜赛经验吗？",
        "required_quick": False,
        "required_formal": True,
        "priority": "medium",
        "sensitive": False,
        "kind": "text",
    },
    "heat_experience": {
        "label": "高温经验",
        "prompt_quick": "你有高温训练或比赛经验吗？",
        "prompt_formal": "你有高温训练或比赛经验吗？",
        "required_quick": False,
        "required_formal": True,
        "priority": "medium",
        "sensitive": False,
        "kind": "text",
    },
    "cold_experience": {
        "label": "低温经验",
        "prompt_quick": "你有低温训练或比赛经验吗？",
        "prompt_formal": "你有低温训练或比赛经验吗？",
        "required_quick": False,
        "required_formal": True,
        "priority": "medium",
        "sensitive": False,
        "kind": "text",
    },
    "altitude_experience": {
        "label": "高海拔经验",
        "prompt_quick": "你有高海拔训练或比赛经验吗？",
        "prompt_formal": "你有高海拔训练或比赛经验吗？",
        "required_quick": False,
        "required_formal": True,
        "priority": "medium",
        "sensitive": False,
        "kind": "text",
    },
    "technical_terrain_experience": {
        "label": "技术地形经验",
        "prompt_quick": "你有技术地形、下坡或碎石路经验吗？",
        "prompt_formal": "你有技术地形、下坡或碎石路经验吗？",
        "required_quick": False,
        "required_formal": True,
        "priority": "medium",
        "sensitive": False,
        "kind": "text",
    },
    "fueling_tolerance": {
        "label": "补给耐受",
        "prompt_quick": "你平时能耐受哪些补给？",
        "prompt_formal": "你在长距离训练/比赛中能耐受哪些补给？",
        "required_quick": False,
        "required_formal": True,
        "priority": "medium",
        "sensitive": False,
        "kind": "text",
    },
    "pole_experience": {
        "label": "登山杖经验",
        "prompt_quick": "你用过登山杖吗？",
        "prompt_formal": "你在训练或比赛中用过登山杖吗？",
        "required_quick": False,
        "required_formal": True,
        "priority": "low",
        "sensitive": False,
        "kind": "text",
    },
    "gear_experience": {
        "label": "装备经验",
        "prompt_quick": "你对补给包、背心、鞋袜等装备有稳定经验吗？",
        "prompt_formal": "你对补给包、换装、鞋袜、头灯等装备有稳定经验吗？",
        "required_quick": False,
        "required_formal": True,
        "priority": "low",
        "sensitive": False,
        "kind": "text",
    },
    "support_arrangements": {
        "label": "支持安排",
        "prompt_quick": "本场有私补、换装包、陪跑或亲友支持吗？",
        "prompt_formal": "本场是否有私补、换装包、陪跑或亲友支持？",
        "required_quick": False,
        "required_formal": True,
        "priority": "medium",
        "sensitive": False,
        "kind": "text",
    },
    "carb_intake_per_hour_g": {
        "label": "每小时碳水摄入",
        "prompt_quick": "可留空后续补充。如果有，每小时大约多少克碳水？",
        "prompt_formal": "长距离和比赛时，你大约能接受每小时多少克碳水？",
        "required_quick": False,
        "required_formal": False,
        "priority": "medium",
        "sensitive": False,
        "kind": "number",
    },
    "hydration_rate_ml_per_hour": {
        "label": "每小时补水量",
        "prompt_quick": "可留空后续补充。如果有，每小时大约多少毫升水？",
        "prompt_formal": "长距离和比赛时，你能接受每小时多少毫升水？",
        "required_quick": False,
        "required_formal": False,
        "priority": "medium",
        "sensitive": False,
        "kind": "number",
    },
    "lowest_temperature_c": {
        "label": "最低温度°C",
        "prompt_quick": "可留空后续补充。用过的最低温度大约多少度？",
        "prompt_formal": "你在夜跑或高海拔时使用过的最低温度大约多少度？",
        "required_quick": False,
        "required_formal": False,
        "priority": "medium",
        "sensitive": False,
        "kind": "number",
    },
    "race_goal": {
        "label": "本场目标",
        "prompt_quick": "本场你的目标是什么？",
        "prompt_formal": "本场你的目标是什么？",
        "required_quick": True,
        "required_formal": True,
        "priority": "high",
        "sensitive": False,
        "kind": "text",
    },
    "red_flag_symptoms": {
        "label": "红旗症状",
        "prompt_quick": "是否有胸痛、晕厥、呼吸困难、发高烧、无法负重等红旗症状？",
        "prompt_formal": "是否有胸痛、晕厥、呼吸困难、发高烧、无法负重、严重脱水或呕吐等红旗症状？",
        "required_quick": False,
        "required_formal": True,
        "priority": "high",
        "sensitive": True,
        "kind": "list",
    },
}

QUICK_FIELDS = [
    "weekly_km",
    "weekly_elevation_m",
    "continuity_weeks",
    "longest_session_distance_km",
    "longest_session_duration_min",
    "injury_status",
    "illness_status",
    "race_goal",
]

FORMAL_FIELDS = [
    "weekly_km",
    "weekly_elevation_m",
    "continuity_weeks",
    "longest_session_distance_km",
    "longest_session_elevation_m",
    "longest_session_duration_min",
    "representative_races",
    "training_break_days",
    "recovery_days",
    "injury_status",
    "illness_status",
    "sleep_hours",
    "subjective_fatigue",
    "night_experience",
    "heat_experience",
    "cold_experience",
    "altitude_experience",
    "technical_terrain_experience",
    "fueling_tolerance",
    "pole_experience",
    "gear_experience",
    "support_arrangements",
    "race_goal",
    "red_flag_symptoms",
]

FORMAL_RECOMMENDED_FIELDS = [
    "carb_intake_per_hour_g",
    "hydration_rate_ml_per_hour",
    "lowest_temperature_c",
]

FORMAL_INPUT_FIELDS = FORMAL_FIELDS + FORMAL_RECOMMENDED_FIELDS

ALL_FIELDS = list(FIELD_SPECS)

RED_FLAG_FIELDS = {
    "chest_pain",
    "fainting",
    "altered_consciousness",
    "severe_breathing_difficulty",
    "persistent_high_fever",
    "whole_body_illness",
    "suspected_fracture",
    "unable_to_bear_weight",
    "acute_severe_pain",
    "severe_dehydration",
    "heat_illness",
    "confusion",
    "uncontrolled_vomiting",
    "official_stop_instruction",
}

YELLOW_HINT_FIELDS = {
    "mild_soreness",
    "fatigue",
    "heat_stress_concern",
    "small_uncertainty",
    "recent_training_break",
}
